pipeline:
  name: Error Categorization
  identifier: Error_Categorization
  projectIdentifier: Invex
  orgIdentifier: Patricio_Playground
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Github
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Validate Error Categorization Rules
                  identifier: Validate_Error_Categorization_Rules
                  spec:
                    shell: Sh
                    command: |-
                      if [ -f ".harness/errors.yaml" ]; then
                          hcli errors validate --yaml-path .harness/errors.yaml
                      else
                          echo "⚠️  .harness/errors.yaml no encontrado — el pipeline continuará sin categorización de errores."
                      fi
              - step:
                  type: Run
                  name: Build and Unit Test
                  identifier: Build_and_Unit_Test
                  spec:
                    connectorRef: Docker_Patricio
                    image: mingc/android-build-box:latest
                    shell: Sh
                    command: ./gradlew testDemoDebug --stacktrace
          buildIntelligence:
            enabled: true
